In [21]:
import numpy as np
list1 = list (range(0,10))
print(list1)

arr1= np.array(list1)
print(arr1[4])

arr2=np.arange(0,9)
print(arr2)

# list2 = list(range(0,10,0.5)) range = 정수 증감만 가능
arr3=np.arange(0,9,0.5) #실수형 

#print(list2)
print(arr3)

arr4=np.full(10,9)
print(arr4)

list2=[[1,2],[3,4]]
print(list2[0][1])

arr5=np.array([[1,2],[3,4]])
print(arr5)

#리스트는 더하기에 열려있다.
list3=[1]
list4=[2]
print(list3+list4)

#어레이는 더하기에 닫혀있다. 서로 연산 가능.
arr1=np.array([1])
arr2=np.array([2])
print(arr1+arr2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
4
[0 1 2 3 4 5 6 7 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[9 9 9 9 9 9 9 9 9 9]
2
[[1 2]
 [3 4]]
[1, 2]
[3]


In [26]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[2,4],[5,6]])
print(np.multiply(arr1,arr2))

[[ 2  8]
 [15 24]]
